- name: Stop and Remove Existing Docker Container
  hosts: all
  tasks:
    - name: Stop the existing container
      become: yes
      docker_container:
        name: dockeransible
        state: stopped
      ignore_errors: yes

    - name: Remove the existing container
      become: yes
      docker_container:
        name: dockeransible
        state: absent
      ignore_errors: yes

- name: Create New Docker Container
  hosts: all
  tasks:
    - name: Pull the Docker image
      become: yes
      docker_image:
        name: chinmayghate/httpd:latest

    - name: Create the new container
      become: yes
      docker_container:
        name: dockeransible
        image: chinmayghate/httpd:latest
        ports:
          - "9000:80"
        detach: yes
